server:
  # 应用服务 WEB 访问端口
  port: 9010

spring:
  output:
    ansi:
      # 终端采用彩色输出
      enabled: always
#  thymeleaf:
  #    cache: false
  h2:
    console:
      settings.web-allow-others: true
      path: /h2
      enabled: true
      settings.trace: true

personal:
  work-dir: ${user.home}/.${spring.application.name}-dev
  console:
    proxy:
      endpoint: http://localhost:3000/
      enabled: true
  security:
    initializer:
      super-admin-username: admin
      super-admin-password: admin
  plugin:
    runtime-mode: dev # 默认prod
    classes-directories:
      - "build/classes"
      - "build/resources"
    lib-directories:
      - "libs"

#  work-dir: ${user.home}/.nas-scraper-dev

logging:
  level:
    cn.acecandy.git.nasscraper: DEBUG

# swagger文档设置
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  show-actuator: true

# actuator 端口设置
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        # api中暴露所有端口
        include: "*"



# 应用名称
#spring:
#  application:
#    name: nas-scraper
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: org.h2.Driver
#    #指定数据库的种类，这里 file意思是文件型数据库
#    url: jdbc:h2:file:~/.${spring.application.name}
#    username: test
#    password: test
#  spring.h2.console.path=/h2
#  h2:
#    console:
#      settings.web-allow-others: true
#      #console url。Spring启动后，可以访问 http://127.0.0.1:8080/h2-console 查看数据库
#      path: /h2
#      enabled: true
#      settings.trace: true
#  sql:
#    init:
#      #创建表的MySql语句位置
#      schema-locations: classpath:sql/schema.sql
#      #插入数据的MySql语句的位置
#      data-locations: classpath:sql/data.sql