server:
  port: 9001
  compression:
    enabled: true

spring:
  application:
    name: nas-scraper
  output:
    ansi:
      # 检查终端是否支持ANSI，是的话就采用彩色输出
      enabled: detect
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    # H2 database configuration.
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:${personal.work-dir}/db/nas-scraper;AUTO_SERVER=TRUE
    #    url: jdbc:h2:file:~/nas-scraper/db/nas-scraper;AUTO_SERVER=TRUE
    username: admin
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  web.resources.static-locations: classpath:/resources/static,classpath:/resources/templates
  # 启用hiddenMethod过滤器
  mvc.hiddenmethod.filter.enabled: true

personal:
  work-dir: ${user.home}/.${spring.application.name}
  external-url: "http://${server.address:localhost}:${server.port}"
  #  work-dir: ${user.home}/.nas-scraper
  plugin:
    root-dir: ${personal.work-dir}/plugins
  attachment:
    resource-mappings:
      - pathPattern: /upload/**
        locations:
          - migrate-from-1.x

springdoc:
  api-docs:
    enabled: false