server:
  # 应用服务 WEB 访问端口
  port: 9001

# 应用名称
spring:
  application:
    name: nas-scraper
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.h2.Driver
    #指定数据库的种类，这里 file意思是文件型数据库
    url: jdbc:h2:file:~/.${spring.application.name}
    username: test
    password: test
  h2:
    console:
      settings.web-allow-others: true
      #console url。Spring启动后，可以访问 http://127.0.0.1:8080/h2-console 查看数据库
      path: /h2
      enabled: true
      settings.trace: true
  sql:
    init:
      #创建表的MySql语句位置
      schema-locations: classpath:schema.sql
      #插入数据的MySql语句的位置
      data-locations: classpath:data.sql

#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
mybatis:
  mapper-locations: classpath:mappers/*xml
  #指定Mybatis的实体目录
  type-aliases-package: cn.acecandy.git.nasscraper.mybatis.entity